# Generated by Django 5.0.6 on 2024-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("tags", models.CharField(max_length=255)),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("author", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
