# Generated by Django 5.0.6 on 2024-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blog",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
