# Generated by Django 5.0.6 on 2024-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_blog_short_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(null=True, upload_to="blog_tumb"),
        ),
    ]
