# Generated by Django 5.0.6 on 2024-05-27 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="publish_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 27, 19, 51, 54, 341334, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
