# Generated by Django 5.0.6 on 2024-05-27 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_blog_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="publish_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
