# Generated by Django 5.0.6 on 2024-06-02 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_blog_publish_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="short_content",
        ),
    ]
