# Generated by Django 5.0.6 on 2024-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_blog_short_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
            ],
        ),
    ]
