# Generated by Django 5.0.6 on 2024-07-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
