# Generated by Django 5.0.6 on 2024-07-19 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="users",
            new_name="user",
        ),
    ]
